<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;
use Drupal\formatage_models\FormatageModelsThemes;
use Stephane888\Debug\Repositories\ConfigDrupal;
use Drupal\Core\Field\FormatterInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Component\Utility\Html;
use Drupal\Core\Url;

/**
 *
 * @file
 * Primary module hooks for formatage models module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * implement hook_entity_operation
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function formatage_models_entity_operation(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->isNew())
    return [];
  /**
   * Ajout la possibilité de duppliquer toutes la configuration.
   */
  $entitytypeId = $entity->getEntityTypeId();
  $entityId = $entity->id();
  switch ($entitytypeId) {
    case 'paragraphs_type':
      return [
        'clone' => [
          'title' => t('Clone by formatage models'),
          'weight' => 50,
          'url' => Url::fromRoute('formatage_models.clone_entity', [
            'entity_type_id' => $entitytypeId,
            'id' => $entityId,
            'etatpe' => 'init',
            'clone_id' => 'none'
          ], [
            'query' => \Drupal::destination()->getAsArray()
          ])
        ]
      ];
      break;
  }
}

/**
 * Implements hook_field_formatter_third_party_settings_form().
 *
 * Adds a textfield for container, label and value.
 */
function formatage_models_field_formatter_third_party_settings_form(FormatterInterface $plugin, FieldDefinitionInterface $field_definition, $view_mode, $form, FormStateInterface $form_state) {
  /**
   * Gestion des balises de structurations html.
   * Dans certaisn cas de figure, on abesoin de supprimer les balises qui
   * encapsule le rendu des champs.
   */
  $remove_container_div = $plugin->getThirdPartySetting('formatage_models', 'remove_container_div', false);
  $element['remove_container_div'] = [
    '#type' => 'checkbox',
    '#title' => t(' Remove container div'),
    '#description' => t('In some cases, we need to remove the tags that encapsulate the rendering of the fields.'),
    '#default_value' => $remove_container_div,
    '#weight' => -29
  ];
  /**
   * Gestion des classes CSS.
   */
  $classes = $plugin->getThirdPartySetting('formatage_models', 'classes', [
    'container' => '',
    'title' => '',
    'value' => '',
    'item' => '',
    'content' => ''
  ]);
  // Pour corriger les elements manquants.
  // on pourrait mettre en place un update.
  $classes += [
    'container' => '',
    'title' => '',
    'value' => '',
    'item' => '',
    'content' => ''
  ];
  $element['classes'] = [
    '#type' => 'details',
    '#title' => t('Field Formatter'),
    '#open' => false,
    '#weight' => -30
  ];
  $element['classes']['container'] = [
    '#type' => 'textfield',
    '#title' => t('Field container class'),
    '#default_value' => $classes['container']
  ];
  $element['classes']['title'] = [
    '#type' => 'textfield',
    '#title' => t('Field label class'),
    '#default_value' => $classes['title']
  ];
  $element['classes']['value'] = [
    '#type' => 'textfield',
    '#title' => t('Field value class (field__items)'),
    '#default_value' => $classes['value']
  ];
  $element['classes']['item'] = [
    '#type' => 'textfield',
    '#title' => t('Class for each item (field__item)'),
    '#default_value' => $classes['item']
  ];
  $element['classes']['content'] = [
    '#type' => 'textfield',
    '#title' => t('Class for each content'),
    '#default_value' => $classes['content'],
    '#description' => "Permet generalement d'appliquer les classes directement sur la balise a"
  ];
  //
  if (\Drupal::moduleHandler()->moduleExists('token')) {
    $element['token_help'] = [
      '#theme' => 'token_tree_link',
      '#token_types' => [
        $field_definition->getTargetEntityTypeId()
      ]
    ];
  }
  return $element;
}

function formatage_models_theme_suggestions_field_alter(&$suggestions, array $variables) {
  if (!empty($variables['element']['#third_party_settings']['formatage_models']['remove_container_div'])) {
    $suggestions[] = 'field__formatage_models_remove_div';
  }
}

/**
 * Implements hook_preprocess_HOOK() for field templates.
 *
 * Adds a custom class to the field's class attribute
 * according to the field formatter settings.
 */
function formatage_models_preprocess_field(&$variables) {
  if (!empty($variables['element']['#third_party_settings']['formatage_models']['remove_container_div'])) {
    //
  }
  // ne s'excute que si et seulement si remove_container_divest à false.
  elseif (!empty($variables['element']['#third_party_settings']['formatage_models']['classes'])) {
    $classContainer = $variables['element']['#third_party_settings']['formatage_models']['classes']['container'];
    $classTitle = $variables['element']['#third_party_settings']['formatage_models']['classes']['title'];
    $classValue = $variables['element']['#third_party_settings']['formatage_models']['classes']['value'];
    $classItem = $variables['element']['#third_party_settings']['formatage_models']['classes']['item'] ?? '';
    $classContent = $variables['element']['#third_party_settings']['formatage_models']['classes']['content'] ?? '';
    
    /** @var \Drupal\Core\Utility\Token $token */
    $token = \Drupal::service('token');
    /** @var \Drupal\Core\Entity\EntityInterface $object */
    $object = $variables['element']['#object'];
    //
    if ($classContainer) {
      $classContainer = $token->replace($classContainer, [
        $object->getEntityTypeId() => $object
      ], [
        'clear' => true
      ]);
      $classContainer = explode(' ', $classContainer);
      foreach ($classContainer as $thisClass) {
        $variables['attributes']['class'][] = Html::escape($thisClass);
      }
    }
    if ($classTitle) {
      $classTitle = $token->replace($classTitle, [
        $object->getEntityTypeId() => $object
      ], [
        'clear' => true
      ]);
      $classTitle = explode(' ', $classTitle);
      foreach ($classTitle as $thisClass) {
        $variables['title_attributes']['class'][] = Html::escape($thisClass);
      }
    }
    //
    if ($classValue) {
      $classValue = $token->replace($classValue, [
        $object->getEntityTypeId() => $object
      ], [
        'clear' => true
      ]);
      $classValue = explode(' ', $classValue);
      foreach ($classValue as $thisClass) {
        $variables['content_attributes']['class'][] = Html::escape($thisClass);
      }
    }
    //
    if ($classItem && !empty($variables['items'])) {
      $classItem = explode(' ', $classItem);
      foreach ($variables['items'] as &$value) {
        $value['attributes']->addClass($classItem);
        //
        if (!empty($classContent) && !empty($value['content'])) {
          if (isset($value['content']['#type']) && $value['content']['#type'] == 'link') {
            $value['content']['#options']['attributes']['class'][] = $classContent;
          }
          else {
            $value['content']['#attributes']['class'][] = $classContent;
          }
        }
      }
    }
  }
}

/**
 * à quoi sert cette function.
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @return array
 */
function addTextareaTreeMultipleMoreAjax(&$form, FormStateInterface $form_state) {
  $parents = $form_state->getTriggeringElement()['#parents'];
  $nbre = count($parents);
  $field = $form;
  for ($i = 0; $i < ($nbre - 2); $i++) {
    if (!empty($parents[$i]) && !empty($field[$parents[$i]]))
      $field = $field[$parents[$i]];
  }
  $form_state->get('nombre_field');
  return $field;
}

/**
 * implement hook_entity_view_alter.
 * On alter le rendu des entités afin d'ajouter l'editeur via le crayon.
 *
 * @deprecated Doit etre deplacer vers contextual_more_links, en tenant compte
 *             des affichages via les vues par champs, des styles et tout autre
 *             données
 *             utiles.
 *            
 * @param array $build
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 */
function formatage_models_entity_view_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  if (\Drupal::currentUser()->hasPermission("formatage_models edit with vuejs") && !\Drupal::service('router.admin_context')->isAdminRoute()) {
    $conf = ConfigDrupal::config('formatage_models.configvuejsedit');
    // On charge l'outil d'edition via le custom bouton.
    $entities = [
      'commerce_product',
      'node',
      'blocks_contents',
      'paragraph',
      'block_content',
      'commerce_product',
      'taxonomy_term'
    ];
    //
    $EntityTypeId = $entity->getEntityTypeId();
    if (!empty($conf['active_edit_config'])) {
      if (in_array($EntityTypeId, $entities) && !empty($build['#' . $EntityTypeId])) {
        $build['formatage_models_quickly_edit'] = [
          '#theme' => 'formatage_models_quickly_edit',
          '#entity' => $build['#' . $entity->getEntityTypeId()]
        ];
      }
    }
  }
}

/**
 * Implement hook_preprocess_page
 */
function formatage_models_preprocess_page(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  
  if ($route_name === 'layout_builder.overrides.node.view' || str_contains($route_name, 'layout_builder.')) {
    $variables['page']['content']['#attached']['library'][] = 'formatage_models/formatage-models-admin';
  }
  elseif ($route_name == 'entity.paragraphs_type.collection') {
    $variables['page']['content']['#attached']['library'][] = 'formatage_models/formatage-models-admin-paragraph';
  }
  
  if (\Drupal::currentUser()->hasPermission("formatage_models edit with vuejs")) {
    // Il faudra que ces liens soient configurable (settings.form).
    $routes = [
      'vuejs_entity.model_choisie_form',
      'buildercv.build_cv'
    ];
    $conf = ConfigDrupal::config('formatage_models.configvuejsedit');
    if (!empty($conf['active_edit_config']) && !in_array($route_name, $routes) && !\Drupal::service('router.admin_context')->isAdminRoute()) {
      /**
       * La div qui contient le point d'entre du fichier JS.
       */
      $variables['page']['content']['entity_edit_vuejs'] = [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#attributes' => [
          'id' => 'entity_edit_by_vuejs'
        ],
        '#attached' => [
          'library' => [
            'formatage_models/edit_entity'
          ]
        ]
      ];
    }
  }
}

/**
 * Permet de supprimer les blocs qui ne sont pas generelement utilisé.
 *
 * @param array $definitions
 * @param array $extra
 */
function formatage_models_plugin_filter_layout__layout_builder_alter(array &$definitions, array $extra) {
  foreach ($definitions as $layout_id => $layout) {
    $module = $layout->getProvider();
    if (!$module) {
      unset($definitions[$layout_id]);
    }
    elseif ($module == 'layout_builder' || $module == 'layout_discovery' || $module == 'bootstrap_barrio') {
      unset($definitions[$layout_id]);
    }
  }
}

/**
 * Implements hook_theme().
 */
function formatage_models_theme($existing, $type, $theme, $path) {
  $hooks = FormatageModelsThemes::getThemeHooks();
  // Template to edit quickly paragraphe.
  $hooks['formatage_models_quickly_edit'] = [
    'preprocess functions' => [
      'template_preprocess_formatage_models_quickly_edit'
    ],
    'render element' => 'element',
    'file' => 'themes/formatage_models.theme.inc'
  ];
  $hooks['formatage_models_search_with_icon'] = [
    'variables' => [
      'content' => NULL
    ]
  ];
  $hooks['formatage_models_search_input_submit'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_formatage_models_search_input_submit'
    ],
    'file' => 'themes/formatage_models.theme.inc'
  ];
  return $hooks;
}

/**
 *
 * @param array $vars
 */
function formatage_models_preprocess_views_view_render_page(&$vars) {
  module_load_include('inc', 'views', 'views.theme');
  template_preprocess_views_view($vars);
  /**
   *
   * @var \Drupal\views\ViewExecutable $view
   */
  $view = $vars['view'];
  //
  $css = $view->display_handler->getOption('view_row_css');
  
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['rows']['attributes'] = $Attribute;
  }
  
  //
  $css = $view->display_handler->getOption('view_header_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['header']['#attributes'] = $Attribute;
  }
  //
  $css = $view->display_handler->getOption('view_form_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    if (!empty($vars['exposed']['#attributes']))
      if (is_object($vars['exposed']['#attributes']))
        $vars['exposed']['#attributes']->addClass($css);
      else {
        foreach ($css as $value) {
          $vars['exposed']['#attributes']['class'][] = $value;
        }
      }
    else
      $vars['exposed']['#attributes'] = $Attribute;
  }
  //
  $css = $view->display_handler->getOption('view_footer_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['footer']['#attributes'] = $Attribute;
  }
}

/**
 *
 * @param array $vars
 */
function formatage_models_preprocess_views_view_render(&$vars) {
  module_load_include('inc', 'views', 'views.theme');
  template_preprocess_views_view($vars);
  /**
   *
   * @var \Drupal\views\ViewExecutable $view
   */
  $view = $vars['view'];
  //
  $css = $view->display_handler->getOption('view_row_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['rows']['attributes'] = $Attribute;
  }
  //
  $css = $view->display_handler->getOption('view_header_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['header']['#attributes'] = $Attribute;
  }
  //
  $css = $view->display_handler->getOption('view_form_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    if (!empty($vars['exposed']['#attributes'])) {
      if (is_array($vars['exposed']['#attributes'])) {
        foreach ($css as $v) {
          $vars['exposed']['#attributes']['class'][] = $v;
        }
      }
      else
        $vars['exposed']['#attributes']->addClass($css);
    }
    else
      $vars['exposed']['#attributes'] = $Attribute;
  }
  //
  $css = $view->display_handler->getOption('view_footer_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['footer']['#attributes'] = $Attribute;
  }
}

/**
 * implement hook_field_formatter_info_alter
 * On a parfois besoin de reduire la quantité de balise autout d'un champs.
 *
 * @param array $info
 */
function formatage_models_field_formatter_info_alter(array &$info) {
  // Let a new field type re-use an existing formatter.
  // $info['text_default']['field_types'][] = 'my_field_type';
}







