field.formatter.settings.formatage_models:
  type: mapping
  label: Formatter settings
  mapping:
    classes:
      type: mapping
      label: Details
      container:
        type: string
        label: Field container class
      title:
        type: string
        label: Field title class
      value:
        type: string
        label: Field value class

field.formatter.settings.formatage_models_fieldgalleries:
  type: mapping
  label: FieldGalleries formatter settings
  mapping:
    foo:
      type: string
      label: Foo

views.display.page_render:
  type: views_display_path
  label: 'Page render display options'
  mapping:
    menu:
      type: mapping
      label: 'Menu'
      mapping:
        type:
          type: string
          label: 'Type'
        title:
          type: text
          label: 'Title'
        description:
          type: text
          label: 'Description'
        weight:
          type: weight
          label: 'Weight'
        enabled:
          type: boolean
          label: 'Enabled'
        expanded:
          type: boolean
          label: 'Expanded'
        menu_name:
          type: string
          label: 'Menu name'
        parent:
          type: string
          label: 'Parent'
        context:
          type: string
          label: 'Context'
    tab_options:
      type: mapping
      label: 'Tab options'
      mapping:
        type:
          type: string
          label: 'Type'
        title:
          type: text
          label: 'Title'
        description:
          type: text
          label: 'Description'
        weight:
          type: weight
          label: 'Weight'
        menu_name:
          type: string
          label: 'Menu name'
    use_admin_theme:
      type: boolean
      nullable: true
      label: 'Use the administration theme when rendering the view page'

views.display.block_render:
  type: views_display
  label: 'Block render display options'
  mapping:
    block_description:
      type: label
      label: 'Block name'
    block_category:
      type: text
      label: 'Block category'
    block_hide_empty:
      type: boolean
      label: 'Hide block if no result/empty text'
    allow:
      type: mapping
      label: 'Allow'
      mapping:
        items_per_page:
          type: boolean
          label: 'Items per page'
